version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.7"
  
conda:
  environment: environment.yml

python:
  install:
    - method: pip
    - requirements: requirements.txt